server:
  #配置端口号
  port: 8080
  servlet:
    #上下文路径
#    context-path: /
    #字符集
    encoding:
      force: true
      enabled: true
      charset: UTF-8

spring:
  datasource:
    #数据库驱动（5.x是com.mysql.jdbc.Driver,8.x是com.mysql.jdbc.Driver）—
    driver-class-name: com.mysql.jdbc.Driver
    #数据库地址
    url: jdbc:mysql://localhost:3306/onebox?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    #数据库的用户名(你使用的数据库）
    username: root
    #密码
    password: 53231323
  mvc:
    #配置RESTFUL风格需要的发送请求方式的配置
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    #文件上传大小设置
    multipart:
      max-file-size: 10GB
      max-request-size: 20GB

mybatis:
  #mapper文件映射位置:类路径下的·····
  mapper-locations: classpath:mapper/**/*.xml
  #扫描实体类的位置
  type-aliases-package: com.turing.onebox.common.model.dto
  configuration:
    #日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰映射
    map-underscore-to-camel-case: true

huang:
  file:
    upload:
      path: E:\cahe\ #上传的文件存储路径